# -*- coding: utf-8 -*-
"""常數與靜態設定（不可變或啟動時固定）"""
import os

GAME_PACKAGE = "jp.co.drecom.wizardry.daphne"
VERSION = "4.4.1"
ADB_HOST = "127.0.0.1"
DEFAULT_IMAGE_DIR = "./images/"

# 初始 list（複製用，勿直接 mutate）
HANDLE_LOOP_LIST_START = [
    "P_chest_open", "P_fastbattle_active", "P_fastbattle_inactive", "P_exit", "P_battle_death_main",
    "P_battle_enemylookingatu", "P_dungeon_suspicious_trader", "P_dungeon_bone_trader",
    "P_gameicon2", "P_gameicon3"
]
DEBUFF_LIST_START = ["P_poison", "P_poison2", "P_curse", "P_rock"]
P_AUTOBATTLE_ACTIVE_LIST = ["P_autobattle_active", "P_autobattle_active0", "P_autobattle_active1"]
P_AUTOBATTLE_INACTIVE_LIST = [
    "P_autobattle_inactive", "P_autobattle_inactive0",
    "P_autobattle_inactive1", "P_autobattle_inactive2"
]
ON9NPC_CLICK_LIST = ["P_ch1_on9npc1", "P_ch2_on9npc1", "P_ch2_on9npc4"]

#劇本提示
script_remainder = {
            "皇女7000g刷錢": {"起點": "任一章城鎮", 
                          "旅館" : ["不休息", "野外補給", "地城露營", "標準房", "豪華房"],
                          "異常狀態": "無"},
            "第二章第一街B1F周回雜物": {"起點": "第二章郊外", 
                              "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                              "異常狀態": "封技"},
            "第二章船二周回雜物": {"起點": "第二章郊外", 
                          "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                          "異常狀態": "封技、封魔、詛咒"},
            "第三章第七區周回巨人": {"起點": "第三章郊外", 
                           "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                           "異常狀態": "封技、封魔、石化", 
                           "提示": ["1. 只會固定使用右下角的技能", "2. 小心爆背包"]},
            "第四章B1F周回雜物": {"起點": "第四章郊外", 
                              "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                              "異常狀態": "中毒"},
            "第四章B4F周回雪山兇鳥帽": {"起點": "第四章郊外", 
                              "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                              "異常狀態": "凍傷",
                              "提示": ["1. 請在指定的2個位置地圖標記", "2. 請對指定的樹木使用逆轉右手"]},
            "第四章B6F周回雜物": {"起點": "第四章郊外", 
                              "旅館" : ["不休息", "野外補給", "地城露營", "標準房", "豪華房"],
                              "異常狀態": "凍傷",
                              "提示": ["1. 請在溫泉及溫泉下方加地圖標記"]},
            "第四章B7F周回雜物": {"起點": "第四章郊外", 
                              "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                              "異常狀態": "中毒"},
            "第四章B7F無限周回雜物": {"起點": "第四章B7F的哈肯", 
                              "旅館" : ["不休息"],
                              "異常狀態": "中毒",
                              "提示": ["1. 不設休息", "2. 請在B7F兩個位置加標記及打通通道", "3. 請不要在B6F增加任何標記"]},
            "第四章B10F雪巨人": {"起點": "任一章城鎮", 
                                "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                                "異常狀態": "無",
                                "提示": ["1. 請在B10F的三個位置加標記"]},
            "擊退敵方勢力(固定開技版)": {"起點": "第二章郊外", 
                              "旅館" : ["地城露營", "標準房", "豪華房"],
                              "異常狀態": "無", 
                              "提示": ["1. 不包括接取任務，請自行接取任務", "2. 固定打三波，請確保有足夠MP上限", "3. 請調速全部法師先動", "4. 請在七號街的哈肯加上標記"]},
            "別離洞窟周回雜物": {"起點": "第一章郊外", 
                         "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                         "異常狀態": "封技、封魔"},
            "百花之庭周回雜物": {"起點": "大地圖百花之庭", 
                         "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                         "異常狀態": "無"},
            "白堊狼穴周回雜物": {"起點": "大地圖白堊狼穴", 
                         "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                         "異常狀態": "石化"},
            "鬼啼島周回雜物": {"起點": "大地圖鬼啼島", 
                         "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                         "異常狀態": "無", 
                         "提示": ["1. 請在B2F哈肯加地圖標記"]},
            "治癒師洞B3F周回雜物": {"起點": "大地圖治癒師洞", 
                         "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                         "異常狀態": "石化",
                         "提示": ["1. 請在B3F哈肯加地圖標記"]},
            "陽炎洞窟長征金箱": {"起點": "第一章城鎮", 
                         "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                         "異常狀態": "封技、封魔、中毒、劇毒", 
                         "提示": ["1. 請確保已開啟所有隱藏區域"]},
            "陽炎洞窟B1F簡易周回雜物": {"起點": "大地圖忍洞", 
                              "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                              "異常狀態": "封技、封魔", 
                              "提示": ["1. 請確保已開啟B1F隱藏區域"]},
            "陽炎洞窟B1F右上打怪周回雜物": {"起點": "大地圖忍洞", 
                                "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                                "異常狀態": "封技、封魔", 
                                "提示": ["1. 請確保已開啟B1F隱藏區域"]},
            "牛牛洞刷精靈甲": {"起點": "第一章城鎮", 
                        "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                        "異常狀態": "封技、封魔、石化", 
                        "提示": ["1. 帶岩石卷軸、神聖守護卷軸、尋寶烈酒各三來交換", "2. 請小心爆背包"]},
            "土之洞窟周回雜物": {"起點": "第一章郊外", 
                         "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                         "異常狀態": "無",
                         "提示": ["1. 需要在小地圖中的入口前一格增加標記", "2. 請事前探明全地圖"]},
            "火之洞窟周回雜物": {"起點": "第一章郊外", 
                         "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                         "異常狀態": "無",
                         "提示": ["1. 請事前探明前往Boss的不同路徑"]},
            "風之洞窟周回雜物": {"起點": "第一章郊外", 
                         "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                         "異常狀態": "無",
                         "提示": ["1. 請事前探明前往Boss的不同路徑"]},
            "光之洞窟周回雜物": {"起點": "第一章郊外", 
                         "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                         "異常狀態": "封技、封魔、詛咒",
                         "提示": ["1. 請事前探明入口區域的地圖"]},
            "水之洞窟周回雜物": {"起點": "第一章郊外", 
                         "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                         "異常狀態": "無",
                         "提示": ["1. 請事前探明前往Boss的不同路徑"]},
            "爐壺靈廟周回": {"起點": "爐壺靈廟郊外", 
                         "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                         "異常狀態": "無",
                         "提示": ["1. 請事前探明前往左上寶箱路徑"]},
            "怨嗟洞窟刷蠍子女遺物周回": {"起點": "第一章郊外", 
                             "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                             "異常狀態": "無", 
                             "提示": ["1. 難度調成「困難」的話遺物等級會高一點", "2. 任務需要懸賞等級7+才出現"]},
            "怨嗟洞窟周回": {"起點": "第一章郊外", 
                             "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                             "異常狀態": "無", 
                             "提示": ["1. 在B3F標一個你想來回的點!!"]},
            "懸賞令周回(蠍子女)": {"起點": "任一章城鎮", 
                           "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                           "異常狀態": "封技、封魔、詛咒",
                            "提示": ["1. 要在蠍子女位置加標記"]},
            "懸賞令周回(牛頭人)": {"起點": "任一章城鎮", 
                           "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                           "異常狀態": "封技、封魔、詛咒",
                            "提示": ["1. 要點兩個標記","2. 怪很痛"]},
            "懸賞令周回(沉穩的騙子布洛克)": {"起點": "任一章城鎮", 
                           "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                           "異常狀態": "無",
                           "提示": ["1. 性格會傾向惡, 請小心使用"]},
            "沙華魚人洞窟B2F雜物周回": {"起點": "第一章郊外", 
                           "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                           "異常狀態": "詛咒、劇毒、封技",
                           "提示": ["1. 需要在B2F哈肯加地圖標記"]},
            "沙華魚人洞窟B3F雜物周回(修女線)": {"起點": "第一章郊外", 
                           "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                           "異常狀態": "詛咒、劇毒、封技",
                           "提示": ["1. 需要在(B2F去B3F的樓梯)和(B3F兩個地方)加地圖標記"]},
            "FF11_B5F周回雜物": {"起點": "FF11活動圖郊外", 
                         "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                         "異常狀態": "無"},
            "FF11_B5F周回標記": {"起點": "FF11活動圖郊外", 
                                     "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                                     "異常狀態": "無",
                         "提示": ["1. 在B5F找個心儀位置標記"]},
            "FF11_B2F周回雜物": {"起點": "FF11活動圖郊外", 
                         "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                         "異常狀態": "無"},
            "FF11_B1F周回雜物": {"起點": "FF11活動圖郊外", 
                                     "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                                     "異常狀態": "無"},
            "FF11_B2F周回挖礦": {"起點": "FF11活動圖郊外", 
                         "旅館" : ["不休息", "野外補給", "標準房", "豪華房"],
                         "異常狀態": "無",
                         "提示": ["1. 要事前在諾森霍洛村設置好自動買十字鎬", "2. 在B2F哈肯右邊的礦點打標記"]},
            "旅館不停休息": {"起點": "任一章城鎮", 
                       "旅館" : ["標準房", "豪華房"],
                       "異常狀態": "無"},
        }

# 常用坐標
L_Minimap = (760, 150)
L_trap_exit = (127, 1120)
L_trap_remove = (450, 1000)
L_heal_char = (730, 1330)
L_heal_button = (820, 830)
L_inn_levelup = (239, 1483)
L_reteam = (771, 1181)
L_map_scalesmall = (100, 1485)
L_map_scalebig = (240, 1485)
L_heal_button_npc = (740, 795)
L_heal_button_main = (840, 795)
L_magnifier = (52, 1181)
L_fasttalking = (240, 1486)

# 常用範圍
R_char_dungeon = (
    (15, 1228, 866, 356),
    (15, 1228, 288, 177),
    (304, 1228, 288, 177),
    (589, 1228, 288, 177),
    (15, 1407, 288, 177),
    (304, 1407, 288, 177),
    (589, 1407, 288, 177),
)
R_chest_map_region = (81, 224, 748, 968)

R_chest_char = {
    1: (68, 1074, 266, 185),
    2: (326, 1074, 266, 185),
    3: (585, 1074, 266, 185),
    4: (68, 1263, 266, 185),
    5: (326, 1263, 266, 185),
    6: (585, 1263, 266, 185),
}


image_files = {
    #重連類
    "P_reconnect": "P_reconnect.png",
    "P_reconnect_button": "P_reconnect_button.png",
    "P_start1": "P_start1.png",
    "P_start2": "P_start2.png",
    "P_comment1": "P_comment1.png",
    "P_comment2": "P_comment2.png",
    "P_comment3": "P_comment3.png",
    "P_backtotitle": "P_backtotitle.png",
    "P_gameicon1": "P_gameicon1.png",
    "P_gameicon2": "P_gameicon2.png",
    "P_gameicon3": "P_gameicon3.png",
    "P_screen_current": "P_screen_current.png",
    "P_screen_previous": "P_screen_previous.png",
    "P_screen_black": "P_screen_black.png",
    "P_download": "P_download.png",
    #角色類
    "P_char1": "P_char1.png",
    "P_char2": "P_char2.png",
    "P_char3": "P_char3.png",
    "P_char4": "P_char4.png",
    "P_char5": "P_char5.png",
    "P_char6": "P_char6.png",
    #角色欄類
    "P_charInfo_bag": "P_charInfo_bag.png",
    "P_charInfo_equip": "P_charInfo_equip.png",
    "P_charInfo_autoequip": "P_charInfo_autoequip.png",
    "P_back_to_warehouse": "P_back_to_warehouse.png",
    "P_charInfo_itemlist": "P_charInfo_itemlist.png",
    #裝備類
    "P_equip_erumon_cloth": "P_equip_erumon_cloth.png",
    #城鎮類
    "P_house": "P_house.png",
    "P_wheel": "P_wheel.png",
    "P_downlist": "P_downlist.png",
    "P_uplist": "P_uplist.png",
    "P_map": "P_map.png",
    "P_guild": "P_guild.png",
    "P_oldplace": "P_oldplace.png",
    "P_inn": "P_inn.png",
    #旅館類
    "P_inn_rest": "P_inn_rest.png",
    "P_inn_standardroom": "P_inn_standardroom.png",
    "P_inn_richroom": "P_inn_richroom.png",
    "P_inn_rest_confirm": "P_inn_rest_confirm.png",
    "P_inn_rest_dialog1": "P_inn_rest_dialog1.png",
    "P_inn_rest_bagrefill": "P_inn_rest_bagrefill.png",
    "P_inn_rest_dialog2": "P_inn_rest_dialog2.png",
    "P_inn_rest_dialog3": "P_inn_rest_dialog3.png",
    "P_inn_levelup_skill": "P_inn_levelup_skill.png",
    "P_inn_levelup_close": "P_inn_levelup_close.png",
    "P_inn_levelup_next": "P_inn_levelup_next.png",
    "P_inn_leave": "P_inn_leave.png",
    #冒險者公會類
    "P_guild_request": "P_guild_request.png",
    "P_guild_request_take": "P_guild_request_take.png",
    "P_guild_request_special": "P_guild_request_special.png",
    "P_guild_request_ninjacave": "P_guild_request_ninjacave.png",
    "P_guild_request_completed": "P_guild_request_completed.png",
    "P_guild_dialog_welcomeback": "P_guild_dialog_welcomeback.png",
    "P_guild_leave": "P_guild_leave.png",
    "P_guild_bounty": "P_guild_bounty.png",
    "P_guild_bounty_back": "P_guild_bounty_back.png",
    "P_guild_bounty_close": "P_guild_bounty_close.png",
    "P_guild_bounty_reward": "P_guild_bounty_reward.png",
    "P_guild_bounty_reward_close": "P_guild_bounty_reward_close.png",
    #懸賞令類
    "P_bounty_dialog1": "P_bounty_dialog1.png",
    "P_bounty_ScorpionGirl_checkpoint1": "P_bounty_ScorpionGirl_checkpoint1.png",
    "P_bounty_ScorpionGirl_minimap1": "P_bounty_ScorpionGirl_minimap1.png",
    "P_bounty_faker_checkpoint1": "P_bounty_faker_checkpoint1.png",
    "P_bounty_faker_checkpoint1B": "P_bounty_faker_checkpoint1B.png",
    "P_bounty_faker_checkpoint2": "P_bounty_faker_checkpoint2.png",
    "P_bounty_faker_dialog1": "P_bounty_faker_dialog1.png",
    "P_bounty_faker_dialog2": "P_bounty_faker_dialog2.png",
    "P_bounty_faker_dialog3": "P_bounty_faker_dialog3.png",
    "P_bounty_faker_dialog4": "P_bounty_faker_dialog4.png",
    "P_bounty_cow_minimap": "P_bounty_cow_minimap.png",
    #詛咒之輪類
    "P_wheel_special_request": "P_wheel_special_request.png",
    "P_wheel_special_request_NinjaCave": "P_wheel_special_request_NinjaCave.png",
    "P_wheel_special_request_confirm": "P_wheel_special_request_confirm.png",
    "P_wheel_basement": "P_wheel_basement.png",
    "P_wheel_saveduke": "P_wheel_saveduke.png",
    "P_wheel_jump": "P_wheel_jump.png",
    "P_wheel_ch1": "P_wheel_ch1.png",
    "P_wheel_ch2": "P_wheel_ch2.png",
    "P_wheel_ch3": "P_wheel_ch3.png",
    "P_wheel_ch4": "P_wheel_ch4.png",
    "P_wheel_ch3_heroback": "P_wheel_ch3_heroback.png",
    "P_wheel_ch4_minerequest": "P_wheel_ch4_minerequest.png",
    "P_wheel_ch4_thetruth": "P_wheel_ch4_thetruth.png",
    "P_wheel_karma": "P_wheel_karma.png",
    "P_wheel_emo_before": "P_wheel_emo_before.png",
    "P_wheel_karma_close": "P_wheel_karma_close.png",
    #郊外類
    "P_outside": "P_outside.png",
    "P_gotodungeon": "P_gotodungeon.png",
    "P_town": "P_town.png",
    "P_village": "P_village.png",
    "P_worldMap": "P_worldMap.png",
    "P_buff": "P_buff.png",
    "P_back": "P_back.png",
    "P_BrokeUpCave": "P_BrokeUpCave.png",
    "P_BrokeUpCave_B2F": "P_BrokeUpCave_B2F.png",
    "P_ch1_outside": "P_ch1_outside.png",
    "P_ch1_B2F": "P_ch1_B2F.png",
    "P_ch1_B3F": "P_ch1_B3F.png",
    "P_ch1_B5F": "P_ch1_B5F.png",
    "P_ch1_B7F": "P_ch1_B7F.png",
    "P_ch2_outside": "P_ch2_outside.png",
    "P_ch2_B1F": "P_ch2_B1F.png",
    "P_ch2_B7F": "P_ch2_B7F.png",
    "P_ch2_B8F": "P_ch2_B8F.png",
    "P_ch3_outside": "P_ch3_outside.png",
    "P_ch3_B1F": "P_ch3_B1F.png",
    "P_ch3_B7F": "P_ch3_B7F.png",
    "P_ch4_outside": "P_ch4_outside.png",
    "P_ch4_B0F": "P_ch4_B0F.png",
    "P_ch4_B4F": "P_ch4_B4F.png",
    "P_ch4_B5F": "P_ch4_B5F.png",
    "P_ch4_B7F": "P_ch4_B7F.png",
    "P_ch4_B7F_inside": "P_ch4_B7F_inside.png",
    "P_ch4_B10F": "P_ch4_B10F.png",
    #溫泉類
    "P_ch1_B7F_checkpoint1": "P_ch1_B7F_checkpoint1.png",
    "P_ch1_B7F_checkpoint2": "P_ch1_B7F_checkpoint2.png",
    "P_onsen_rest": "P_onsen_rest.png",
    "P_onsen_rest2": "P_onsen_rest2.png",
    "P_onsen_dontrest": "P_onsen_dontrest.png",
    "P_onsen_dialog1": "P_onsen_dialog1.png",
    #大地圖類
    "P_chapter1": "P_chapter1.png",
    "P_chapter2": "P_chapter2.png",
    "P_chapter3": "P_chapter3.png",
    "P_chapter4": "P_chapter4.png",
    "P_map_ninjacave": "P_map_ninjacave.png",
    "P_map_cowcave": "P_map_cowcave.png",
    "P_map_FlowerGarden": "P_map_FlowerGarden.png",
    "P_map_WhiteWolf": "P_map_WhiteWolf.png",
    "P_map_WhiteWolf_B1F": "P_map_WhiteWolf_B1F.png",
    "P_map_WhiteWolf_B2F": "P_map_WhiteWolf_B2F.png",
    "P_map_temple": "P_map_temple.png",
    "P_map_scalesmall": "P_map_scalesmall.png",
    "P_map_scalebig": "P_map_scalebig.png",
    #地城類
    "P_exit": "P_exit.png",
    "P_Cmove": "P_Cmove.png",
    "P_automove": "P_automove.png",
    "P_automove2": "P_automove2.png",
    "P_chest": "P_chest.png",
    "P_autochest": "P_autochest.png",
    "P_automark": "P_automark.png",
    "P_noChest": "P_noChest.png",
    "P_noPath": "P_noPath.png",
    "P_magnifier": "P_magnifier.png",
    "P_minimap_close": "P_minimap_close.png",
    "P_dungeon_suspicious_trader": "P_dungeon_suspicious_trader.png",
    "P_dungeon_suspicious_trader_buy2000": "P_dungeon_suspicious_trader_buy2000.png",
    "P_dungeon_gain": "P_dungeon_gain.png",
    "P_dungeon_bone_trader": "P_dungeon_bone_trader.png",
    "P_dungeon_bone_trader_buybone": "P_dungeon_bone_trader_buybone.png",
    "P_dungeon_bone_trader_gotbone": "P_dungeon_bone_trader_gotbone.png",
    "P_dungeon_bone_trader_dontbuy": "P_dungeon_bone_trader_dontbuy.png",
    #戰鬥類
    "P_autobattle_active": "P_autobattle_active.png",
    "P_autobattle_active0": "P_autobattle_active0.png",
    "P_autobattle_active1": "P_autobattle_active1.png",
    "P_autobattle_inactive": "P_autobattle_inactive.png",
    "P_autobattle_inactive0": "P_autobattle_inactive0.png",
    "P_autobattle_inactive1": "P_autobattle_inactive1.png",
    "P_autobattle_inactive2": "P_autobattle_inactive2.png",
    "P_fastbattle_active": "P_fastbattle_active.png",
    "P_fastbattle_inactive": "P_fastbattle_inactive.png",
    "P_battle_noSPMP": "P_battle_noSPMP.png",
    "P_battle_bar": "P_battle_bar.png",
    "P_battle_baseattack": "P_battle_baseattack.png",
    "P_aoe_holy_special": "P_aoe_holy_special.png",
    "P_aoe_dark": "P_aoe_dark.png",
    "P_aoe_earth": "P_aoe_earth.png",
    "P_aoe_earth_special": "P_aoe_earth_special.png",
    "P_aoe_fire": "P_aoe_fire.png",
    "P_aoe_light": "P_aoe_light.png",
    "P_aoe_nil": "P_aoe_nil.png",
    "P_aoe_confirm": "P_aoe_confirm.png",
    "P_battle_wait": "P_battle_wait.png",
    "P_battle_enemylookingatu": "P_battle_enemylookingatu.png",
    "P_battle_enemygone": "P_battle_enemygone.png",
    "P_battle_letthemgo": "P_battle_letthemgo.png",
    "P_battle_dropsomething": "P_battle_dropsomething.png",
    "P_battle_enemywantfight": "P_battle_enemywantfight.png",
    "P_battle_blindside": "P_battle_blindside.png",
    "P_battle_fight": "P_battle_fight.png",
    "P_battle_cost": "P_battle_cost.png",
    "P_battle_detail": "P_battle_detail.png",
    "P_battle_death_fire": "P_battle_death_fire.png",
    "P_battle_death_main": "P_battle_death_main.png",
    "P_battle_death_npc1": "P_battle_death_npc1.png",
    "P_battle_death_npc2": "P_battle_death_npc2.png",
    #異常狀態
    "P_poison": "P_poison.png",
    "P_poison2": "P_poison2.png",
    "P_curse": "P_curse.png",
    "P_banSkill" : "P_banSkill.png",
    "P_rock" : "P_rock.png",
    "P_heal_will": "P_heal_will.png",
    #開箱類
    "P_chest_open": "P_chest_open.png",
    "P_chest_notopen": "P_chest_notopen.png",
    "P_chest_close": "P_chest_close.png",
    "P_chest_trap": "P_chest_trap.png",
    "P_chest_gain": "P_chest_gain.png",
    "P_chest_ar": "P_chest_ar.png",
    "P_chest_lost": "P_chest_lost.png",
    "P_chest_scary": "P_chest_scary.png",
    "P_chest_scaryIcon": "P_chest_scaryIcon.png",
    "P_chest_scary_dialog": "P_chest_scary_dialog.png",
    #補給類
    "P_bag_tidy": "P_bag_tidy.png",
    "P_bag_buybutton": "P_bag_buybutton.png",
    "P_bag_refill": "P_bag_refill.png",
    "P_bag_refill_complete": "P_bag_refill_complete.png",
    "P_heal_confirm": "P_heal_confirm.png",
    "P_heal_close": "P_heal_close.png",
    "P_heal_button1": "P_heal_button1.png",
    "P_heal_button2": "P_heal_button2.png",
    #第一章地圖
    "P_ch1_on9npc1": "P_ch1_on9npc1.png",
    "P_ch1_on9npc2": "P_ch1_on9npc2.png",
    "P_ch1_on9npc2_option2": "P_ch1_on9npc2_option2.png",
    "P_ch1_on9npc3": "P_ch1_on9npc3.png",
    #第二章地圖
    "P_ch2_on9npc1": "P_ch2_on9npc1.png",
    "P_ch2_on9npc2": "P_ch2_on9npc2.png",
    "P_ch2_on9npc2_option1": "P_ch2_on9npc2_option1.png",
    "P_ch2_on9npc3": "P_ch2_on9npc3.png",
    "P_ch2_on9npc3_2": "P_ch2_on9npc3_2.png",
    "P_ch2_on9npc4": "P_ch2_on9npc4.png",
    "P_ch2_B7F_dialog1": "P_ch2_B7F_dialog1.png",
    "P_ch2_B7F_option1": "P_ch2_B7F_option1.png",
    "P_ch2_B7F_dialog2": "P_ch2_B7F_dialog2.png",
    "P_ch2_B7F_option2": "P_ch2_B7F_option2.png",
    "P_ch2_B8F_dialog1": "P_ch2_B8F_dialog1.png",
    "P_ch2_B8F_option1": "P_ch2_B8F_option1.png",
    "P_Farm_ch2B9F_checkpoint1": "P_Farm_ch2B9F_checkpoint1.png",
    "P_Farm_ch2B9F_minimap1": "P_Farm_ch2B9F_minimap1.png",
    "P_Farm_ch2B9F_chestarea1": "P_Farm_ch2B9F_chestarea1.png",
    "P_Farm_ch2B9F_chestarea2": "P_Farm_ch2B9F_chestarea2.png",
    "P_Farm_ch2B9F_chestarea3": "P_Farm_ch2B9F_chestarea3.png",
    "P_Farm_ch2B9F_chestarea4": "P_Farm_ch2B9F_chestarea4.png",
    "P_Farm_ch2B9F_chestarea5": "P_Farm_ch2B9F_chestarea5.png",
    "P_Farm_ch2B9F_chestarea6": "P_Farm_ch2B9F_chestarea6.png",
    #第三章地圖
    "P_ch3B7F_glant1": "P_ch3B7F_glant1.png",
    "P_ch3B7F_glant2": "P_ch3B7F_glant2.png",
    #第四章地圖
    "P_ch4_B1F_checkpoint1": "P_ch4_B1F_checkpoint1.png",
    "P_ch4_B1F_minimap1": "P_ch4_B1F_minimap1.png",
    "P_ch4_B4F_minimap1": "P_ch4_B4F_minimap1.png",
    "P_ch4_B4F_minimap2": "P_ch4_B4F_minimap2.png",
    "P_ch4_B4F_minimap3": "P_ch4_B4F_minimap3.png",
    "P_ch4_B4F_minimap4": "P_ch4_B4F_minimap4.png",
    "P_ch4_B4F_minimap5": "P_ch4_B4F_minimap5.png",
    "P_ch4_B4F_minimap6": "P_ch4_B4F_minimap6.png",
    "P_ch4_B6F_checkpoint1": "P_ch4_B6F_checkpoint1.png",
    "P_ch4_B6F_checkpoint2": "P_ch4_B6F_checkpoint2.png",
    "P_ch4_B6F_minimap1": "P_ch4_B6F_minimap1.png",
    "P_ch4_B6F_minimap2": "P_ch4_B6F_minimap2.png",
    "P_ch4_B6F_minimap3": "P_ch4_B6F_minimap3.png",
    "P_ch4_B7F_minimap1": "P_ch4_B7F_minimap1.png",
    "P_ch4_B7F_minimap2": "P_ch4_B7F_minimap2.png",
    "P_ch4_B10F_checkpoint1": "P_ch4_B10F_checkpoint1.png",
    "P_ch4_B10F_checkpoint2": "P_ch4_B10F_checkpoint3.png",
    "P_ch4_B10F_checkpoint3": "P_ch4_B10F_checkpoint3.png",
    "P_ch4_B10F_minimap1": "P_ch4_B10F_minimap1.png",
    "P_ch4_B10F_minimap2": "P_ch4_B10F_minimap2.png",
    "P_ch4_B10F_until1": "P_ch4_B10F_until1.png",
    "P_ch4_B10F_until2": "P_ch4_B10F_until2.png",
    "P_ch4_B10F_until3": "P_ch4_B10F_until3.png",
    "P_ch4_on9npc1": "P_ch4_on9npc1.png",
    "P_ch4_on9npc2": "P_ch4_on9npc2.png",
    "P_ch4_on9npc2_2": "P_ch4_on9npc2_2.png",
    "P_ch4_on9npc3": "P_ch4_on9npc3.png",
    "P_ch4_on9npc3A": "P_ch4_on9npc3A.png",
    "P_ch4_on9npc3B": "P_ch4_on9npc3B.png",
    "P_ch4_on9npc1B": "P_ch4_on9npc1B.png",
    "P_ch4_on9npc2B": "P_ch4_on9npc2B.png",
    "P_ch4_on9npc4": "P_ch4_on9npc4.png",
    "P_ch4_on9npc4A": "P_ch4_on9npc4A.png",
    "P_ch4_on9npc4B": "P_ch4_on9npc4B.png",
    "P_dungeon_suspicious_trader_lookgoods": "P_dungeon_suspicious_trader_lookgoods.png",
    #裝備類
    "P_ch4_SnowHat": "P_ch4_SnowHat.png",
    #土之洞窟
    "P_EarthCave": "P_EarthCave.png",
    "P_EarthCave_B1F": "P_EarthCave_B1F.png",
    #火之洞窟
    "P_FireCave": "P_FireCave.png",
    "P_FireCave_B1F": "P_FireCave_B1F.png",
    "P_FireCave_checkpoint1": "P_FireCave_checkpoint1.png",
    "P_FireCave_minimap1": "P_FireCave_minimap1.png",
    "P_FireCave_wayA": "P_FireCave_wayA.png",
    "P_FireCave_wayB": "P_FireCave_wayA.png",
    "P_FireCave_wayC": "P_FireCave_wayC.png",
    "P_CaveGoal": "P_CaveGoal.png",
    #風之洞窟
    "P_WindCave": "P_WindCave.png",
    "P_WindCave_B1F": "P_WindCave_B1F.png",
    "P_Cave_BigRock1": "P_Cave_BigRock1.png",
    "P_Cave_BigRock1_2": "P_Cave_BigRock1_2.png",
    #光之洞窟
    "P_LightCave": "P_LightCave.png",
    "P_LightCave_B1F": "P_LightCave_B1F.png",
    "P_LightCave_Map": "P_LightCave_Map.png",
    "P_LightCave_minimap1": "P_LightCave_minimap1.png",
    "P_LightCave_minimap2": "P_LightCave_minimap2.png",
    "P_LightCave_checkpoint1": "P_LightCave_checkpoint1.png",
    "P_LightCave_checkpoint2": "P_LightCave_checkpoint2.png",
    #水之洞窟
    "P_WaterCave": "P_WaterCave.png",
    "P_WaterCave_B1F": "P_WaterCave_B1F.png",
    "P_WaterCave_checkpoint1": "P_WaterCave_checkpoint1.png",
    "P_WaterCave_minimap1": "P_WaterCave_minimap1.png",
    #怨嗟洞窟
    "P_GrudgeCave": "P_GrudgeCave.png",
    "P_GrudgeCave_B3F": "P_GrudgeCave_B3F.png",
    "P_GrudgeCave_B4F": "P_GrudgeCave_B4F.png",
    "P_GrudgeCave_checkpoint1": "P_GrudgeCave_checkpoint1.png",
    "P_GrudgeCave_minimap1": "P_GrudgeCave_minimap1.png",
    #別離洞窟
    "P_Minimap_BrokeUpCave_B2F": "P_Minimap_BrokeUpCave_B2F.png",
    "P_Minimap_BrokeUpCave_B3F": "P_Minimap_BrokeUpCave_B3F.png",
    "P_BrokeUpCave_checkpoint1": "P_BrokeUpCave_checkpoint1.png",
    #牛牛洞窟
    "P_guild_request_cowcave": "P_guild_request_cowcave.png",
    "P_cowcave_dialog1": "P_cowcave_dialog1.png",
    "P_cowcave_dialog2": "P_cowcave_dialog2.png",
    "P_cowcave_dialog3": "P_cowcave_dialog3.png",
    "P_cowcave_dialog4": "P_cowcave_dialog4.png",
    "P_cowcave_dialog5": "P_cowcave_dialog5.png",
    "P_cowcave_dialog6": "P_cowcave_dialog6.png",
    "P_cowcave_dialog7": "P_cowcave_dialog7.png",
    "P_cowcave_dialog8": "P_cowcave_dialog8.png",
    "P_cowcave_dialog9": "P_cowcave_dialog9.png",
    "P_cowcave_dialog10": "P_cowcave_dialog10.png",
    "P_cowcave_dialog11": "P_cowcave_dialog11.png",
    "P_cowcave_dialog12": "P_cowcave_dialog12.png",
    "P_cowcave_dialog13": "P_cowcave_dialog13.png",
    "P_cowcave_checkpoint1": "P_cowcave_checkpoint1.png",
    "P_cowcave_checkpoint2": "P_cowcave_checkpoint2.png",
    "P_cowcave_checkpoint3": "P_cowcave_checkpoint3.png",
    "P_cowcave_checkpoint4": "P_cowcave_checkpoint4.png",
    "P_cowcave_checkpoint5": "P_cowcave_checkpoint5.png",
    "P_cowcave_minimap2": "P_cowcave_minimap2.png",
    "P_cowcave_minimap4": "P_cowcave_minimap4.png",
    "P_cowcave_minimap5": "P_cowcave_minimap5.png",
    "P_cowcave_mushroom1": "P_cowcave_mushroom1.png",
    "P_cowcave_mushroom2": "P_cowcave_mushroom2.png",
    "P_cowcave_mushroom_get": "P_cowcave_mushroom_get.png",
    "P_cowcave_mushroom_allget": "P_cowcave_mushroom_allget.png",
    "P_cowcave_herbs": "P_cowcave_herbs.png",
    "P_cowcave_herbs_get": "P_cowcave_herbs_get.png",
    "P_cowcave_holly": "P_cowcave_holly.png",
    "P_cowcave_rock": "P_cowcave_rock.png",
    "P_cowcave_sake": "P_cowcave_sake.png",
    "P_cowcave_trade": "P_cowcave_trade.png",
    "P_cowcave_trade_continue": "P_cowcave_trade_continue.png",
    "P_cowcave_trade_end": "P_cowcave_trade_end.png",
    "P_cowcave_tradeother": "P_cowcave_tradeother.png",
    "P_cowcave_trade_dialog1": "P_cowcave_trade_dialog1.png",
    "P_cowcave_trade_dialog2": "P_cowcave_trade_dialog2.png",
    "P_cowcave_trade_dialog3": "P_cowcave_trade_dialog3.png",
    #陽炎洞窟
    "P_ninjacave_chestarea1": "P_ninjacave_chestarea1.png",
    "P_ninjacave_chestarea2": "P_ninjacave_chestarea2.png",
    "P_ninjacave_chestarea3": "P_ninjacave_chestarea3.png",
    "P_ninjacave_trapbutton": "P_ninjacave_trapbutton.png",
    "P_ninjacave_dialog1": "P_ninjacave_dialog1.png",
    "P_ninjacave_dialog2": "P_ninjacave_dialog2.png",
    "P_ninjacave_dialog3": "P_ninjacave_dialog3.png",
    "P_ninjacave_dialog4": "P_ninjacave_dialog4.png",
    "P_ninjacave_dialog5": "P_ninjacave_dialog5.png",
    "P_ninjacave_dialog6": "P_ninjacave_dialog6.png",
    "P_ninjacave_dialog6_optionA": "P_ninjacave_dialog6_optionA.png",
    "P_ninjacave_dialog6_optionA_after": "P_ninjacave_dialog6_optionA_after.png",
    "P_ninjacave_dialog6_optionB": "P_ninjacave_dialog6_optionB.png",
    "P_ninjacave_dialog7": "P_ninjacave_dialog7.png",
    "P_ninjacave_dialog7_optionA": "P_ninjacave_dialog7_optionA.png",
    "P_ninjacave_dialog8": "P_ninjacave_dialog8.png",
    "P_ninjacave_dialog8_optionC": "P_ninjacave_dialog8_optionC.png",
    "P_ninjacave_dialog9": "P_ninjacave_dialog9.png",
    "P_ninjacave_dialog10": "P_ninjacave_dialog10.png",
    "P_ninjacave_dialog11": "P_ninjacave_dialog11.png",
    "P_ninjacave_checkpoint1": "P_ninjacave_checkpoint1.png",
    "P_ninjacave_checkpoint2": "P_ninjacave_checkpoint2.png",
    "P_ninjacave_checkpoint3": "P_ninjacave_checkpoint3.png",
    "P_ninjacave_checkpoint4": "P_ninjacave_checkpoint4.png",
    "P_ninjacave_checkpoint5": "P_ninjacave_checkpoint5.png",
    "P_ninjacave_checkpoint6": "P_ninjacave_checkpoint6.png",
    "P_ninjacave_checkpoint7": "P_ninjacave_checkpoint7.png",
    "P_ninjacave_checkpoint8": "P_ninjacave_checkpoint8.png",
    "P_ninjacave_checkpoint9": "P_ninjacave_checkpoint9.png",
    "P_ninjacave_checkpoint10": "P_ninjacave_checkpoint10.png",
    "P_ninjacave_checkpoint11": "P_ninjacave_checkpoint11.png",
    "P_ninjacave_checkpoint12": "P_ninjacave_checkpoint12.png",
    "P_ninjacave_checkpoint13": "P_ninjacave_checkpoint13.png",
    "P_ninjacave_checkpoint14": "P_ninjacave_checkpoint14.png",
    "P_ninjacave_checkpoint15": "P_ninjacave_checkpoint15.png",
    "P_ninjacave_checkpoint16": "P_ninjacave_checkpoint16.png",
    "P_ninjacave_checkpoint17": "P_ninjacave_checkpoint17.png",
    "P_ninjacave_checkpoint18": "P_ninjacave_checkpoint18.png",
    "P_ninjacave_checkpoint19": "P_ninjacave_checkpoint19.png",
    "P_ninjacave_checkpoint20": "P_ninjacave_checkpoint20.png",
    "P_ninjacave_minimap1": "P_ninjacave_minimap1.png",
    "P_ninjacave_minimap2": "P_ninjacave_minimap2.png",
    "P_ninjacave_minimap3": "P_ninjacave_minimap3.png",
    "P_ninjacave_minimap4": "P_ninjacave_minimap4.png",
    "P_ninjacave_minimap4B": "P_ninjacave_minimap4B.png",
    "P_ninjacave_minimap5": "P_ninjacave_minimap5.png",
    "P_ninjacave_minimap6": "P_ninjacave_minimap6.png",
    "P_ninjacave_minimap7": "P_ninjacave_minimap7.png",
    "P_ninjacave_minimap8": "P_ninjacave_minimap8.png",
    "P_ninjacave_minimap9": "P_ninjacave_minimap9.png",
    "P_ninjacave_minimap9B": "P_ninjacave_minimap9B.png",
    "P_ninjacave_minimap10": "P_ninjacave_minimap10.png",
    "P_ninjacave_minimap11": "P_ninjacave_minimap11.png",
    "P_ninjacave_minimap12": "P_ninjacave_minimap12.png",
    "P_ninjacave_minimap12B": "P_ninjacave_minimap12B.png",
    "P_ninjacave_minimap13": "P_ninjacave_minimap13.png",
    "P_ninjacave_minimap14": "P_ninjacave_minimap14.png",
    "P_ninjacave_minimap15": "P_ninjacave_minimap15.png",
    "P_ninjacave_minimap15_screen": "P_ninjacave_minimap15_screen.png",
    "P_ninjacave_minimap15B": "P_ninjacave_minimap15B.png",
    "P_ninjacave_minimap16": "P_ninjacave_minimap16.png",
    "P_ninjacave_minimap17": "P_ninjacave_minimap17.png",
    "P_ninjacave_minimap17B": "P_ninjacave_minimap17B.png",
    "P_ninjacave_minimap18": "P_ninjacave_minimap18.png",
    "P_ninjacave_minimap19": "P_ninjacave_minimap19.png",
    "P_ninjacave_minimap19B": "P_ninjacave_minimap19B.png",
    "P_ninjacave_minimap20": "P_ninjacave_minimap20.png",
    #第二章擊敗敵方勢力
    "P_expCH2_checkpoint1": "P_expCH2_checkpoint1.png",
    "P_expCH2_dialog1": "P_expCH2_dialog1.png",
    "P_expCH2_dialog2": "P_expCH2_dialog2.png",
    "P_expCH2_dialog3": "P_expCH2_dialog3.png",
    "P_expCH2_optionB": "P_expCH2_optionB.png",
    #皇女腳本
    "P_Minimap_ch3_B5F": "P_Minimap_ch3_B5F.png",
    "P_Minimap_ch3_B4F": "P_Minimap_ch3_B4F.png",
    "P_dialog_knight": "P_dialog_knight.png",
    "P_dialog_era": "P_dialog_era.png",
    "P_gonow": "P_gonow.png",
    "P_7000g_notime": "P_7000g_notime.png",
    "P_dialog_goin": "P_dialog_goin.png",
    "P_dialog_listentoher": "P_dialog_listentoher.png",
    "P_notonly": "P_notonly.png",
    "P_uncle_left": "P_uncle_left.png",
    "P_uncle_middle": "P_uncle_middle.png",
    "P_uncle_right": "P_uncle_right.png",
    "P_girl_left": "P_girl_left.png",
    "P_girl_middle": "P_girl_middle.png",
    "P_girl_right": "P_girl_right.png",
    "P_grandpa_left": "P_grandpa_left.png",
    "P_grandpa_middle": "P_grandpa_middle.png",
    "P_grandpa_right": "P_grandpa_right.png",
    "P_dialog_uncle": "P_dialog_uncle.png",
    "P_dialog_girl": "P_dialog_girl.png",
    "P_dialog_grandpa": "P_dialog_grandpa.png",
    "P_dialog_why": "P_dialog_why.png",
    "P_dialog_leftherhere": "P_dialog_leftherhere.png",
    "P_dialog_auok": "P_dialog_auok.png",
    "P_dialog_disagree": "P_dialog_disagree.png",
    "P_dialog_emo": "P_dialog_emo.png",
    "P_dialog_try": "P_dialog_try.png",
    "P_dialog_lazydo": "P_dialog_lazydo.png",
    "P_coin": "P_coin.png",
    "P_on9princess": "P_on9princess.png",
    #鬼啼島
    "P_GhostIsland": "P_GhostIsland.png",
    "P_GhostIsland_B2F": "P_GhostIsland_B2F.png",
    "P_GhostIsland_on9npc1": "P_GhostIsland_on9npc1.png",
    #治癒師洞
    "P_HealerCave": "P_HealerCave.png",
    "P_HealerCave_B3F": "P_HealerCave_B3F.png",
    #沙華魚人洞窟
    "P_FireDragon": "P_FireDragon.png",
    "P_FireDragon_B2F": "P_FireDragon_B2F.png",
    "P_FireDragon_B3F_minimap1": "P_FireDragon_B3F_minimap1.png",
    "P_FireDragon_B3F_minimap2": "P_FireDragon_B3F_minimap2.png",
    "P_FireDragon_B3F_minimap3": "P_FireDragon_B3F_minimap3.png",
    #爐壺靈廟
    "P_2Wbone": "P_2Wbone.png",
    "P_2Wbone_minimap1": "P_2Wbone_minimap1.png",
    "P_2Wbone_minimap2": "P_2Wbone_minimap2.png",
    "P_2Wbone_minimap3": "P_2Wbone_minimap3.png",
    "P_2Wbone_minimap4": "P_2Wbone_minimap4.png",
    "P_2Wbone_checkpoint1": "P_2Wbone_checkpoint1.png",
    "P_2Wbone_checkpoint2": "P_2Wbone_checkpoint2.png",
    "P_2Wbone_checkpoint3": "P_2Wbone_checkpoint3.png",
    #金礦石任務
    "P_GoldOre_checkpoint1": "P_GoldOre_checkpoint1.png",
    "P_GoldOre_minimap1": "P_GoldOre_minimap1.png",
    "P_GoldOre_checkpoint2": "P_GoldOre_checkpoint2.png",
    "P_GoldOre_minimap2": "P_GoldOre_minimap2.png",
    "P_GoldOre_getOre": "P_GoldOre_getOre.png",
    "P_GoldOre_Ore": "P_GoldOre_Ore.png",
    #FF11活動
    "P_FF11_B1F": "P_FF11_B1F.png",
    "P_FF11_B2F": "P_FF11_B2F.png",
    "P_FF11_B5F": "P_FF11_B5F.png",
    "P_FF11Cave": "P_FF11Cave.png",
    "P_FF11_B5F_minimap1": "P_FF11_B5F_minimap1.png",
    "P_FF11_get": "P_FF11_get.png",
    "P_FF11_ore": "P_FF11_ore.png",
    "P_FF11_ore2": "P_FF11_ore2.png",
    "P_FF11_village": "P_FF11_village.png",
}

